# Generated by Django 5.2.4 on 2025-07-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_reservation_alter_plat_categorie_alter_plat_prix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='telephone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
