# Generated by Django 5.2.3 on 2025-07-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=150)),
                ('surface', models.FloatField()),
                ('nombre_chambre', models.IntegerField()),
                ('niveau', models.IntegerField(choices=[(1, '1 étoile(s)'), (2, '2 étoile(s)'), (3, '3 étoile(s)'), (4, '4 étoile(s)'), (5, '5 étoile(s)')])),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=20)),
                ('appartements', models.ManyToManyField(related_name='clients', to='monapp.appartement')),
            ],
        ),
    ]
