# Generated by Django 5.2.4 on 2025-07-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='appartements/'),
        ),
    ]
