# Generated by Django 5.2.4 on 2025-07-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0002_appartement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clients/'),
        ),
    ]
